import pandas as pd

# List of CSV files generated by your scripts
csv_files = ["snmp_traps.csv", "netflow_flows.csv", "snmp_poll.csv"]

# Read each CSV into a DataFrame
dfs = [pd.read_csv(file) for file in csv_files]

# Convert the 'timestamp' column to datetime format in each DataFrame
for df in dfs:
    df["timestamp"] = pd.to_datetime(df["timestamp"])

# Concatenate all DataFrames into a single one
merged_df = pd.concat(dfs, ignore_index=True)

# Sort the merged DataFrame in chronological order
merged_df = merged_df.sort_values("timestamp")

# Save the unified dataset into a new CSV file
merged_df.to_csv("merged_dataset.csv", index=False)
print("Unified dataset saved as 'merged_dataset.csv'.")
